name: get-scores-and-deploy-site

on:
  schedule:
    - cron: '0 */1 * * *' # Runs every 1 hour

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm ci

      - name: Run script
        run: node scoreboard.js

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: new-index-html
          path: index.html

      - name: Checkout GitHub Pages branch
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0

      - name: Replace existing index.html
        uses: actions/download-artifact@v2
        with:
          name: new-index-html
          path: index.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: '.'
