name: get-scores-and-deploy-site

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 min

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: '.'

      - name: Set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm ci

      - name: Run script
        run: node scoreboard.js

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: master
          folder: '.'
          clean: true # removes all existing files in the branch before deploying
